### ISSUE TITLE
Do not import pytest in setup.py to make it compatible with pipenv

### ISSUE THREAD

**Issue by abotalov** [RKrahl/pytest-dependency#13]
Currently pipenv doesn't allow to install pytest-dependency.

As said in the following ticket, pipenv is unable to install pytest-dependency due to poorly written `setup.py`:
https://github.com/kennethreitz/pipenv/issues/878

**Comment by RKrahl** [comment]
Hmm, “poorly written `setup.py`”? I could just as well claim that pipenv is poorly written if it fails to install the packages in the proper order.  (Sorry for the late reply, I was busy with other stuff lately.)
