### ISSUE TITLE
Update pypi

### ISSUE THREAD

**Issue by mirandaconrado** [RKrahl/pytest-dependency#16]
Thanks for this! Would you mind updating the pypi index? The fix to not depend on import anymore from https://github.com/RKrahl/pytest-dependency/commit/7691ce8aca8e297e56a76e2174b39868fc856f0b is really useful.

**Comment by RKrahl** [comment]
Please do not open a new issue for something that is already done!  Note that the [plan for the next release](https://github.com/RKrahl/pytest-dependency/milestone/3) is already well advanced but not yet completely finished.  Duplicate of #13.
