### ISSUE TITLE
Skip dependency check if pytest is called with -k switch

### ISSUE THREAD

**Issue by benjaminweb** [RKrahl/pytest-dependency#18]

**Comment by RKrahl** [comment]
Erm, why? Could you elaborate?

**Comment by benjaminweb** [comment]
Sure:
If I decide to test a specific function `my_function` (because I do some work on it), I expect the test to run.
Since `-k` does not let run the dependency, the test for `my_function` is not ran.
I expected the inverse.

**Comment by RKrahl** [comment]
So, in your particular use case, the `-k` switch happens to run only only single test, but not its dependencies.  You may add `–ignore-unknown-dependency` to the command line, this switch has specifically been added for this situation.

In other use cases, the `-k` switch might select many tests, including all dependencies. If in this case one of the dependency fails, the user would probably expect pytest-dependency to do its job and skip the dependent test.

**Comment by benjaminweb** [comment]
I have not been aware of the `--ignore-unknown-dependency` switch. Thanks for pointing that out.

> In other use cases, the -k switch might select many tests, including all dependencies. If in this case one of the dependency fails, the user would probably expect pytest-dependency to do its job and skip the dependent test.

True.

Closing this issue. Resolved by learning about `--ignore-unknown-dependency` switch.

**Comment by benjaminweb** [comment]
Or would it be more intuitive to execute the dependency automatically (since the -k matched test would otherwise not run at all)?
