### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/pytest-dependency#2]
Add more documentation.  Need at least a text explaining the basic concept. What is this good for, statement of the problem that this plugin solves. How to use it.

**Comment by Midnighter** [comment]
I can't believe pytest hasn't had this so far... I would love to use this feature, could you add a simple example to the readme on how to mark dependencies between two tests or is your code still very much in flux?

**Comment by RKrahl** [comment]
Sure I could and should add more documentation, including examples.  I don't think that the stability of the API is an issue that could restrain this.  The only problem is … well, I need to get around to do it.  That is what this open issue is about.  I can only work in my spare time on this project.

In the mean time, have I look into the tests.  `tests/test_02_simple_dependency.py` provides pretty generic examples for the basic usage (watch for the multi line string arguments to `ctestdir.makepyfile()`).  `tests/test_03_param.py` shows how to combine the dependency marks with parameterizing tests.  A rather complex example of a real application can be found in another project using pytest-dependency, here: [icatproject/python-icat:tests/test_06_ids.py](https://github.com/icatproject/python-icat/blob/master/tests/test_06_ids.py).

**Comment by Midnighter** [comment]
Thank you very much that's really helpful. And believe me, I know the pain of developing something that meets your own high standards in your spare time.

**Comment by RKrahl** [comment]
Obviously, documentation is never finished.  Now I wrote something, I hope will cover the basic stuff.  At least I believe it's enough to close this issue for now.

@Midnighter: if you got some time, maybe you could have a look at [the online documentation](http://pythonhosted.org/pytest-dependency/) and drop some comments.  For the package author, it's always difficult to assess what is obvious to the user and what needs more explanations.

**Comment by Midnighter** [comment]
The docs look good to me. Thank you for the addition. I'll let you know if I come across any uncertainties/missing descriptions.
