### ISSUE TITLE
Cross file dependency check

### ISSUE THREAD

**Issue by iboyperson** [RKrahl/pytest-dependency#23]
I am unsure whether this a feature request or an issue but I am attempting to have a test in one file depend on a test from another. I will give a visual example below.

    tests/file1.py
    --- class1()
    --- --- method1()
    tests/file2.py
    --- class2()
    --- --- method2()

Now I want method2 to depend on the success of method1. Is there some way I am missing to do this? I have done the "Class1::method1" in the depends for method2.

**Comment by RKrahl** [comment]
No, your are not overlooking something. It is indeed a feature that is not implemented yet.

In fact, this is a duplicate of #3: at the moment, dependencies are checked in module scope only. What you are requesting now is dependency checking in session scope.

**Comment by iboyperson** [comment]
Is this a feature that is planned to be implemented? I am by no means a expert at python but the solution JoeSc proposed in issue 3 seemed like a good one.

**Comment by iboyperson** [comment]
Closing this as it is essentially a duplicate
