### ISSUE TITLE
Add a way to configure the scope

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/pytest-dependency#3]
For the moment, the scope of the dependencies is hard coded to `module`.  That means that a test can only be marked as dependent on a test in the same module, but cannot depend on a test in a different module.  The backend class `DependencyManager` is in principle also capable to work on `session` scope.  But the calling hooks do not use the optional `scope` argument in the `getManager()` call.

The difficulty is that I have no idea how to define a clean API to configure the scope from the calling tests.

**Comment by JoeSc** [comment]
Take a look at
https://github.com/JoeSc/pytest-dependency/commit/d282e6df1248e8617156fdedeba2e6ffef9ce374

I think it does what you want, and is sane.  All the existing tests still pass.
Let me know if you approve or want changes and I can add some documentation

**Comment by Formartha** [comment]
I am waiting for this to be merged in as well :)

**Comment by babaMar** [comment]
Me too :+1:

**Comment by bentsi** [comment]
+1

**Comment by MathReynaud** [comment]
+ 1

**Comment by juicedatom** [comment]
I'm all up for this as well!

**Comment by fbarbu15** [comment]
Waiting for this as well! Thanks
