### ISSUE TITLE
always skipped

### ISSUE THREAD

**Issue by xyd113** [RKrahl/pytest-dependency#36]
env:
pytest==5.3.4
pytest-dependency==0.4.0(installed by pip3 install pytest-dependency)

code:
@pytest.mark.dependency()
    def test_a(self):
        # fail
        assert True

    @pytest.mark.dependency()
    def test_b(self):
        # pass
        assert True

    @pytest.mark.dependency(depends=["test_a", "test_b"])
    def test_c(self):
        assert True

result:
![image](https://user-images.githubusercontent.com/39815896/72802433-bbaa3600-3c86-11ea-8d4d-95ff1c4cd6ea.png)

problem：
test_c is skipped when test_a and test_b are passed。

**Comment by RKrahl** [comment]
Your code looks strange: what is that `self` argument in your tests?  If I run the example as is, I get an error `"fixture 'self' not found"` from pytest as expected.

I guess your tests are in fact methods of a class, so the code really looks like:
```python
import pytest

class TestCase:

    @pytest.mark.dependency()
    def test_a(self):
        # fail
        assert True

    @pytest.mark.dependency()
    def test_b(self):
        # pass
        assert True

    @pytest.mark.dependency(depends=["test_a", "test_b"])
    def test_c(self):
        assert True
```

If that is the case, you need to add the name of the class to the dependencies like this:
```python
import pytest

class TestCase:

    @pytest.mark.dependency()
    def test_a(self):
        # fail
        assert True

    @pytest.mark.dependency()
    def test_b(self):
        # pass
        assert True

    @pytest.mark.dependency(depends=["TestCase::test_a", "TestCase::test_b"])
    def test_c(self):
        assert True
```

See the [documentation](https://pytest-dependency.readthedocs.io/en/0.4.0/usage.html#using-test-classes).

**Comment by xyd113** [comment]
@RKrahl 
thank you for your reply，this solved my problem.
