### ISSUE TITLE
Using multiple dependency markers for methods that depend on more than one parametrized functions does not work

### ISSUE THREAD

**Issue by anishradvani** [RKrahl/pytest-dependency#38]
I have a bunch of tests running in Pytest that depend on a series of tests running in a class. I'm using pytest-dependency to run some other tests in another module, but only if all the tests in this dependency class pass. 

This is the set of tests that absolutely NEED to pass for me to proceed with the rest of the tests. It has two methods inside the class:

```
@pytest.mark.dependency()
class TestThis:
    """Test steady state of network."""

    @pytest.mark.parametrize("device", params_this)
    def test_that(self, device: str) -> None:
        do something
        assert xyz == abc

    @pytest.mark.parametrize("device", params_that)
    def test_this_as_well(self, device: str) -> None:
        do something
        assert xyz == abc
```

Now, when I add only one dependency marker in the tests that follow, it works as expected. If any of the tests in TestThis::test_that fail, the rest of the tests are skipped.

```
@pytest.mark.dependency(
    depends=instances(

            "tests/test_xyz.py::TestThis::test_that",
            params_this,
        ),
    scope="session",
)
class TestEverything:
    """Class to test everything."""
```

However, when I add two dependency markers like below, the tests proceed as usual even if one or more of the tests within the dependencies fail. This is unexpected behavior AFAIK. 

```
@pytest.mark.dependency(
    depends=instances(

            "tests/test_xyz.py::TestThis::test_that",
            params_this,
        ),
    scope="session",
)
@pytest.mark.dependency(
    depends=instances(

            "tests/test_xyz.py::TestThis::test_this_as_well",
            params_that,
        ),
    scope="session",
)
class TestEverything:
    """Class to test everything."""
```
I found that if a test fails from the test_that method, but the tests from test_this_as_well all pass, it proceeds with the test in the TestEverything method. But if tests in the second dependency marker fail, it skips the tests as expected. Need to figure out what the solution for this is, or if this is a bug. Can we use multiple dependency markers like this?

Looking for possible solutions to this problem, because I cannot combine the two dependency methods into one for the rest of my test-suite to consume.

**Comment by RKrahl** [comment]
Trying to boil down your setting to a minimal example, I believe you are trying to do something like this:
```
import pytest

@pytest.mark.dependency()
@pytest.mark.xfail(reason="deliberate fail")
def test_a():
    assert False

@pytest.mark.dependency()
def test_b():
    pass

@pytest.mark.dependency(depends=["test_a"])
@pytest.mark.dependency(depends=["test_b"])
def test_c(request):
    pass
```

Indeed, if you try this, `test_c` will not be skipped, even though `test_a` fails. In fact, using multiple `pytest.mark.dependency` markers for a single test simply does not work. The dependencies in the markers will not be combined, but the dependencies from the second marker will override those from the first. That is why the dependency on `test_a` will simply be ignored. This seem to be consistent with what you describe in your setting. The simple example must be rewritten as follows to work:
```
import pytest

@pytest.mark.dependency()
@pytest.mark.xfail(reason="deliberate fail")
def test_a():
    assert False

@pytest.mark.dependency()
def test_b():
    pass

@pytest.mark.dependency(depends=["test_a", "test_b"])
def test_c(request):
    pass
```

In your setting, you might want to try something like the following:
```
@pytest.mark.dependency(
    depends=instances(

            "tests/test_xyz.py::TestThis::test_that",
            params_this,
        ) + instances(

            "tests/test_xyz.py::TestThis::test_this_as_well",
            params_that,
        ),
    scope="session",
)
class TestEverything:
    """Class to test everything."""
```

**Comment by anishradvani** [comment]
Hey @RKrahl thanks for your response. Appreciate the work you have done on this package. I did try the exact setting you suggested, but I find any combination of it skips all the tests in the dependency marker.

I do not have the ```@pytest.mark.xfail``` marker on the test class that needs to pass, but I don't think that should matter.

```
tests/test_steady_state.py::TestThis::test_that[a] PASSED                                 
tests/test_steady_state.py::TestThis::test_that[b] PASSED                                 
tests/test_steady_state.py::TestThis::test_that[c] PASSED                                 
tests/test_steady_state.py::TestThis::test_that[d] PASSED                                  
tests/test_steady_state.py::TestThis::test_that[e] PASSED                                  
tests/test_steady_state.py::TestThis::test_this_as_well[a] PASSED                          
tests/test_steady_state.py::TestThis::test_this_as_well[b] PASSED                          
tests/test_steady_state.py::TestThis::test_this_as_well[c] PASSED                          
tests/test_steady_state.py::TestThis::test_this_as_well[d] PASSED                           
tests/test_steady_state.py::TestThis::test_this_as_well[e] PASSED                           
tests/test_all.py::TestEverything::test_pre[test_content0-xyz] SKIPPED                                                                       
tests/test_all.py::TestEverything::test_body[test_content0-xyz] SKIPPED                                                                       
tests/test_all.py::TestEverything::test_post[test_content0-xyz] SKIPPED                                                                       
tests/test_all.py::TestEverything::test_pre[test_content1-xyz] SKIPPED                                                                           
tests/test_all.py::TestEverything::test_body[test_content1-xyz] SKIPPED                                                                           
tests/test_all.py::TestEverything::test_post[test_content1-xyz] SKIPPED  
```

Is this something you're able to replicate? I have the same "session" scope in my dependency settings as well.

**Comment by anishradvani** [comment]
Also, it would be great to be able to have pytest-dependency run based on a class dependency rather than a method, for example

```python
@pytest.mark.dependency(
    depends=instances(

            "tests/test_xyz.py::TestThis",
            params_this,
    scope="session",
)
class TestEverything:
    """Class to test everything."""
```

**Comment by RKrahl** [comment]
@anishradvani, I'm sorry, I'm not able to debug your code.  First of all, I can't do this because you posted only fragments of it by now, so I don't have the full picture.  But even if you had posted your full code, I can't do this simply because I don't have the time to do your home work.

If you believe to see some behavior that hints on a bug in pytest-dependency, I have to ask you to create a minimal example (in the same manner as I did above) of code that reproduces the alleged bug.

Regarding your last comment: actually this does work, see #39.

**Comment by RKrahl** [comment]
This issue originally was about that multiple dependency markers for a single test does not work. Actually this was never supposed to work. I'll therefore close as invalid.
