### ISSUE TITLE
[Feature]Dependent to run on condition when upstream dependency are failed or not success?

### ISSUE THREAD

**Issue by aayush-jain18** [RKrahl/pytest-dependency#42]
Is it possible to include a feature/param to run dependent when the status of dependencies is failed or not a success?

**Comment by RKrahl** [comment]
I'm not sure if I understand what you are trying to achieve. Why would you want to run a dependent test if any of dependencies did not succeed? It's the very purpose of the dependency marker to skip the dependent test in this case. If you don't want this, why don't you just remove the dependency marker?

**Comment by aayush-jain18** [comment]
I have some test-case that run on some special condition or when a test-case is failed

**Comment by RKrahl** [comment]
@aayush-jain18 could you please elaborate? I can't help you if I don't understand what you want.

Please provide a concrete (and preferably minimal) example that illustrates what you are trying to achieve.

**Comment by RKrahl** [comment]
Closing as invalid.
