### ISSUE TITLE
Dependency is skipped when I rename test within dependency.

### ISSUE THREAD

**Issue by piotr-lesniak** [RKrahl/pytest-dependency#47]
2 files:

test_abc.py

```
import pytest


class TestAbc:
    @pytest.mark.dependency()
    def test_abc(self):
        assert False

```

and test_def.py:

```
import pytest


class TestDef:
    @pytest.mark.dependency(depends=['test_abc.py::TestAbc::test_abc'], scope='package')
    def test_def(self):
        pass
```

It works as expected now: test_abc fails, test_def is skipped.

When I rename test_def within dependency like this:

```
import pytest


class TestDef:
    @pytest.mark.dependency(depends=['test_abc.py::TestAbc::test_abc'], scope='package')
    @pytest.mark.dependency(name='test_two')
    def test_def(self):
        pass

```

actual behaviour is: test_abc fails, test_def passes - is that correct behaviour? Shouldn't test_def be skipped?

**Comment by RKrahl** [comment]
No.  With pytest, you cannot apply the same marker twice to the same test.  If you try to do so, the second instance of the marker will override the first one.  So what your second version of `test_def.py` essentially does is:
```python
import pytest

class TestDef:
    @pytest.mark.dependency(name='test_two')
    def test_def(self):
        pass
```

What you probably wanted to do is:
```python
import pytest

class TestDef:
   @pytest.mark.dependency(name='test_two', depends=['test_abc.py::TestAbc::test_abc'], scope='package')
    def test_def(self):
        pass
```
