### ISSUE TITLE
Test suite incompatibility with pytest 6.2

### ISSUE THREAD

**Issue by jayvdb** [RKrahl/pytest-dependency#50]
I am seeing a lot of errors running the test suite with pytest 6.2.2.  I assume they are from 6.2.0 but I havent isolated when they started.

https://github.com/pytest-dev/pytest/blob/master/doc/en/changelog.rst might give some clues to what causes it

**Comment by RKrahl** [comment]
Thanks for notifying me about this!  The reason for the test failures is that that the diagnostic output for `pytest --verbose` has been changed in the case of skipped tests.  Previous pytest versions would emit something like:
```
test_no_skip.py::test_a SKIPPED
test_no_skip.py::test_b PASSED
test_no_skip.py::test_c PASSED
test_no_skip.py::test_d PASSED
```
while pytest 6.2.0 and newer add the message given as argument to `pytest.skip()` like:
```
test_no_skip.py::test_a SKIPPED (explicit skip)
test_no_skip.py::test_b PASSED
test_no_skip.py::test_c PASSED
test_no_skip.py::test_d PASSED
```
So the expected output in the tests does not match anymore.

Note that this ony affects the test suite.  The plugin should still work fine with pytest 6.2.2.

**Comment by RKrahl** [comment]
Just for the records, I believe the change that caused of this incompatibility was pytest-dev/pytest#7208.
