### ISSUE TITLE
Check pytest-dependency with test classes

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/pytest-dependency#6]
I did not experiment much with test classes by now.  Need to verify that the plugin also works for test classes, should add appropriate tests to the test suite and add the usage for test classes to the documentation.

**Comment by somnambWl** [comment]
Great idea with this package, but for me it does not work in classes and is useless because of this. I tried to name dependencies as well, but all tests marked with dependency decorator which depends on something are skipped.

**Comment by RKrahl** [comment]
It turns out that pytest-dependency works just fine with test classes and the usage is straight forward.

There is only one issue: for methods of test classes, the default name is just the method name.  This may cause conflicts if there is a function having the same name outside the class or if there is another class with a method of the same name. Such conflicts may have unexpected results.  To mend this, I will prepend the class name to the default test name.
