### ISSUE TITLE
when the dependency case use @pytest.mark.parametrize,  depened cases was skipped,although the dependency test is success

### ISSUE THREAD

**Issue by huangliweiwei** [RKrahl/pytest-dependency#69]
Result：
test_dependency.py::TestStep::test_01[1] 01 case 1
PASSED
test_dependency.py::TestStep::test_01[20] 01 case 20
PASSED
**test_dependency.py::TestStep::test_02 SKIPPED
test_dependency.py::TestStep::test_03 SKIPPED**
test_dependency.py::TestStep::test_04 04 case
PASSED

Code：
class TestStep:
    @pytest.mark.smoke
    @pytest.mark.parametrize('param', [1, 20])
    @pytest.mark.dependency()
    def test_01(self, param):
        print "01 case", param
        assert True

    @pytest.mark.dependency(depends=["TestStep::test_01"])
    def test_02(self):
        print "02 case"
        assert False

    @pytest.mark.dependency(depends=["TestStep::test_01"])
    def test_03(self):
        print "03 case"
        assert True

    def test_04(self):
        print "04 case"
        assert True
pytest.main(['-sv'])

**Comment by huangliweiwei** [comment]
slove

**Comment by q2qiang** [comment]
I want to know how you solved it
